### ISSUE TITLE
Create DOI for this data

### ISSUE THREAD

**Issue by j-wags** [MCompChem/fep-benchmark#1]
This is a great dataset. Thanks for putting it together! 

You might consider using [Zenodo](https://zenodo.org/) to create a DOI for this data. This will allow other researchers to recognize your contribution and cite you when they use this data in their work. Zenodo will capture the state of this repository at one time, and if you make changes, correct typos, or add data later, you can make a new release and have a separate DOI assigned to the new version.

We have been very happy with using Zenodo to track data in our project. You can see an example [here](https://zenodo.org/record/3256444#.XSyDVntlDOQ). I'd be happy to work with you to get this configured. It should take under an hour.

**Comment by MCompChem** [comment]
Thanks for the suggestion. I created a DOI with Zenodo and added it to the README.
