### ISSUE TITLE
Sanitize commit history?

### ISSUE THREAD

**Issue by j-wags** [MCompChem/fep-benchmark#2]
In case any of this data is sensitive, I wanted to point out that files that are uploaded and later deleted are still available in the git history. It is possible to remove this data from the history using some git commands ([here is one method](https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github)) 

You can view the commit history of this repository here https://github.com/MCompChem/fep-benchmark/commits/master

It looks like you removed some data from the `cmet` folder, and I would be happy to work with you to clean that up if the data is sensitive.

**Comment by MCompChem** [comment]
Thanks for pointing this out.
