### ISSUE TITLE
Provide a list of the FEP calculations that were carried out to obtain these?

### ISSUE THREAD

**Issue by drmeister** [MCompChem/fep-benchmark#4]
Hello, thank you for this resource!

If it's not too much trouble - could you provide the graph of the FEP calculations that were carried out to obtain these values?

Starting ligand -> ending ligand or a two-column CSV file or any other human-readable format would be fine.

eg:
CHEMBL1078774 -> CHEMBL1093087
...

**Comment by MCompChem** [comment]
The requested files were added to the repository e.g. results_edges_5ns.csv

**Comment by drmeister** [comment]
Thank you very much!

I have enhanced Cando so that it can set up calculations starting from the files in this repository.
I'll be in touch once I get some results.
