### ISSUE TITLE
Inconsistency between results here and in paper.

### ISSUE THREAD

**Issue by AnguseZhang** [MCompChem/fep-benchmark#5]
Dear Developers, 
   I found the results here are not consistent with those in your paper https://pubs.acs.org/doi/pdf/10.1021/acs.jcim.0c00900.
   For example, the pairwise RMSE  of tnks2 reported in paper is 2.02 kcal/mol , but when I use data here https://github.com/MCompChem/fep-benchmark/blob/master/tnks2/results_edges_5ns.csv , I get 1.20kcal/mol. I wonder if there is some misleading when processing data.

**Comment by MCompChem** [comment]
Hi AnguseZhang,
thanks for reporting this issue.
The difference arises from the fact that you likely calculated ddG RMSE over all edges listed in the file. However, pairwise RMSE was evaluated on all ligand pairs irrespective of if there was actually a calculated edge in the FEP map or not. This makes it easier to compare results between different methods, however if there are a few edges with larger errors that affect the difference between two subclusters of compounds in the map like in this case this will disproportionately affect the results.
I will close this issue.
