### ISSUE TITLE
bottoming out the assay for CDK8?

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [MCompChem/fep-benchmark#6]
Hello!

Looking in the .csv for CDK8, it looks like there are repeated values 

https://github.com/MCompChem/fep-benchmark/blob/master/cdk8/results_20ns.csv
i.e. -11.22 and -11.46

Looking at the primary citation, it looks like these are 4 nm or 5 nm affinities (or in the last decimal place quoted to) --- is it possible that these compounds are bottoming out the assay? If so, it is possible that these could be higher affinity than reported? And if so on top of that, does that mean that they can be used for free energy calculations or not? Or should they be handled differently, i.e. assessing categorical success, or using larger error bars for some compounds.

cc. @dominicrufa @jchodera @dfhahn

**Comment by maxentile** [comment]
Thank you for making this resource available!

I also recently noticed a few repeated values for a couple of these systems (after finding that some of the relative binding free energy labels were exactly 0).

![repeated-values](https://user-images.githubusercontent.com/5759036/109745139-6c307c00-7ba1-11eb-801e-9d660c6248b5.jpg)

I don't know enough about how these experimental values are processed to know if a small number of repeated values is to be expected given measurement precision, unit conversions, etc... Any guidance on whether these values should be handled differently in subsequent analysis as @hannahbrucemacdonald suggests would be greatly appreciated!

<details>

```python
from collections import Counter
from glob import glob

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt


field = 'Exp. ΔG'
paths = dict([(path.split('/')[-2], path) for path in glob('fep-benchmark/*/results_20ns.csv')])
for target in paths:
    print(f'{target}:\t {paths[target]}')
print()


def report_duplicates(counter: Counter, title: str):
    n, n_unique = sum(counter.values()), len(counter)
    print(title)
    print(f'# ΔG values:\t\t{n}\n# unique ΔG values:\t{n_unique}')
    
    
    values, repeats = np.array(counter.most_common()).T
    print(f'values in interval [{min(values), max(values)}]')
    
    inds = np.argsort(-repeats)
    for i in inds:
        if repeats[i] > 1:
            print(f'value {values[i]} repeated {int(repeats[i])} times')
    print('-'*20)
    

def plot_duplicates(counter: Counter, title: str):
  
    values, repeats = np.array(counter.most_common()).T

    plt.scatter(values, repeats, s=3)
    plt.xlabel(f'{field} value')
    plt.ylabel('# occurrences')
    plt.yticks([1,2,3,4,5])
    plt.ylim(0.5,5.5)
    
    subtitle = '(no repeated values)'
    if max(repeats) > 1:
        subtitle = f'({values[np.argmax(repeats)]} repeated {int(max(repeats))} times)'
    
    plt.title(f'{title}\n{subtitle}')

plt.figure(figsize=(6,12))
for i, target in enumerate(paths.keys()):
    plt.subplot(4, 2, i+1) # 8 subplots
    df = pd.read_csv(paths[target])
    counter = Counter(df[field])
    plot_duplicates(counter, target)
    report_duplicates(counter, target)
plt.tight_layout()

plt.savefig('repeated-values.jpg', dpi=200, bbox_inches='tight')
```
</details>

**Comment by mkgilson** [comment]
I did a couple of spot checks:

For the CDK8 paper https://reader.elsevier.com/reader/sd/pii/S0960894X16300609?token=1F4BDE09A84B7431A680CFB53C47E6D9339AB5EB3486EE314905F5EF41BDDDC7D72FA95AC91E06637C767D3DEDFBD93A&originRegion=us-east-1&originCreation=20210728183936
There are in fact multiple ligands listed with IC50 7 nM (to one significant digit, which is fine), which I believe corresponds to 
the repeat value for CDK8. 

For Syk, there are ligands with IC50s of 8.5nM and 8.6 nM, which I think account for the apparent repeat. That said, the Syk SDfile included on this github page appears to have one error, see my issue here.

For the molecules are you are suspicious of here, you can drop the chembl id into the simple search bar in BindingDB to see the molecule quickly and then check the article for the data.

**Comment by jchodera** [comment]
The actual assay used for CDK8 is described in [footnote 29](https://www.sciencedirect.com/science/article/pii/S0960894X16300609#b0145), which does not give the test concentrations of ligand used but does note the concentrations of CDK8 (5 nM) and the competitive ligand (10 nM):

> FRET based Lanthascreen binding competition assay: A dye-labeled ATP competitive probe served as a FRET acceptor upon binding to CDK8 labeled with a strepavidin-Eu-chelate (via a biotinylated anti His antibody). The result was a fluorescence signal at 647 nm. When this ATP competitive probe is displaced by an inhibitor, the signal is repressed. CDK8 used for this assay was co-expressed with Cyclin C (Invitrogen #PV4402, 80% purity). The assay procedure for an assay in 1536 well plate format was performed as follows: 2 μL CDK8/biotin-anti-His Ab/SA-Eu mix in assay buffer (pH 7.5) were pipetted into the wells of a micro plate. 1 μL compound in 20 mM Hepes buffer/5% DMSO was added. The plate was shaken for 30 s and incubated for 20 min at rt. 2 μL Alexa647-probe in assay buffer were added. The plate was shaken for 30 s again and incubated for 60 min at rt in the dark. Then the plate was read on a Perkin Elmer Envision (mode LANCE/TRF, excitation 340 nm emission 650 nm). The assay buffer was 50 mM Hepes pH 7.5 (Merck # 1.10110), 10 mM MgCl2 (Merck #1.05833), 1 mM EGTA (Merck #1.08435), 0.01% Brij-35 (Pierce #28316). The final concentrations of the reaction components in 5 μL total assay volume were: 1% DMSO (Merck # 1.02950), 5 nM CDK8/Cyclin C (Invitrogen #PV4402), 2 nM biotin-a-His Ab (Invitrogen #PV6089), 2 nM SA-Europium (Invitrogen #PV5899), 10 nM Alexa647-Tracer (Invitrogen #PV5592).

As noted [here](https://elifesciences.org/articles/57264), the limiting component (in this case, CDK8) should be several-fold lower than the measured Kd to give a reliable measure of Kd. As such, any Kds <= about 10 nM should be considered suspect and unreliable, as 10 nM represents the reliable floor for this assay.

**Comment by mkgilson** [comment]
Interesting point.  I got focused on the accuracy of the data transcription question rather than the reliability of the assay for this data, because of an apparent transcription error in the Syk data (see Issue 1). 

If I squint at the scatter plot of FEP vs expt in the paper, I could imagine that the exptl data sort of hit a wall at about -11.8 kcal/mol, but it's hardly definitive.

**Comment by MCompChem** [comment]
Thanks for pointing this out. I will add a note to the CDK8 case about the assay.

**Comment by MCompChem** [comment]
Note that dG values are rounded by the Schrodinger software.
