### ISSUE TITLE
Apparent error in SYK sdfile

### ISSUE THREAD

**Issue by mkgilson** [MCompChem/fep-benchmark#7]
Hi,

The IC50 for CHEMBL3265032 is given as 10000 nm in the SDfile, which would give a binding FE of -6.8 kcal/mol, but the data tables give -11.06, which appears to be consistent with the figures as well.  Also the value of -11.06 is consistent with the article, which gives an IC50 of 7.7 nM for this compound. See Compound 68 in Table 4.

Regards,
Mike

PS Credit where due: Mike Potter at VeraChem is the one who spotted this.

**Comment by MCompChem** [comment]
Hi,
thanks Mike & Mike for pointing this out. I have fixed this error in the sdf.
Regards,
Christina
